import {
  MatButtonModule,
  MatChipsModule,
  MatFormFieldModule,
  MatIconModule,
  MatProgressSpinnerModule,
  MatProgressBarModule,
  MatCardModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatCheckboxModule,
  MatRadioModule,
  MatSidenavModule,
  MatToolbarModule,
  MatMenuModule,
  MatSnackBarModule,
  MatDialogModule,
  MatButtonToggleModule,
  MatTabsModule,
  MatListModule,
  MatInputModule
} from '@angular/material';

export const MATERIAL: any[] = [
  MatButtonModule,
  MatChipsModule,
  MatFormFieldModule,
  MatIconModule,
  MatProgressSpinnerModule,
  MatProgressBarModule,
  MatCardModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatCheckboxModule,
  MatRadioModule,
  MatSidenavModule,
  MatToolbarModule,
  MatMenuModule,
  MatSnackBarModule,
  MatDialogModule,
  MatButtonToggleModule,
  MatTabsModule,
  MatListModule,
  MatInputModule
];